package ar.edu.unju.fo.poo.POOPractico4.util;

public enum Ciudades {
	SALTA,SAN_MIGUEL_TUCUMAN,SAN_SALVADOR_JUJUY,CORDOBA,POSADAS,PARANA,SGO_ESTERO,LA_PLATA,SANTA_ROSA,RAWSON,USHUAIA,VIEDMA,SANTA_FE;
}
