package ar.edu.unju.fo.poo.POOPractico4.util;

public enum Nombres {
	ARMANDO,ALBERTO,ALEJANDRO,ALEJO,ALVARO,BRUNO,BENITO,CAMILO,CASSIO,DAMIAN,JORGE,ESTEBAN,MARIANA,MELISA,VERONICA,AYELEN,GISELA,YESICA,JUDITH,GRACIELA,CAROLINA,TERESA,ANDREA
}
